# Generated by Django 6.1.1 on 2026-09-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
