# Generated by Django 6.1.1 on 2026-10-02 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_notification_unique_notification_per_booking_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'booking_date', 'booking_time'], name='booking_provider_date_time_idx'),
        ),
    ]
