# Generated by Django 6.1.1 on 2026-10-02 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_booking_booking_provider_date_time_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_customers', to='services.service')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', '-created_at'], name='saved_service_customer_created')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'service'), name='unique_saved_service')],
            },
        ),
    ]
