# Generated by Django 6.1.1 on 2026-10-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_savedservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.service'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('PAYMENT_SUCCESSFUL', 'Payment Successful'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('PROVIDER_STARTED', 'Provider Started Service'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('SAVED_SERVICE_UNAVAILABLE', 'Saved Service Unavailable')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('recipient', 'service', 'notification_type'), name='unique_notification_per_service_type'),
        ),
    ]
