# Generated by Django 6.1.1 on 2026-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_notification_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MOCK', 'Mock Payment'), ('STRIPE', 'Stripe')], default='MOCK', max_length=20),
        ),
    ]
