# Generated by Django 6.1.1 on 2026-10-06 04:52

import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to='service_images/', validators=[services.validators.validate_uploaded_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[services.validators.validate_uploaded_image]),
        ),
    ]
