# Generated by Django 6.1.1 on 2026-10-06 05:47

import django.db.models.deletion
import services.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_serviceimage_image_alter_userprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='media/', validators=[services.validators.validate_uploaded_image])),
                ('media_type', models.CharField(choices=[('PROFILE', 'Profile'), ('SERVICE', 'Service')], max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.service')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'media_type'], name='media_owner_type_idx'), models.Index(fields=['service', 'visibility'], name='media_service_visibility_idx')],
            },
        ),
    ]
