# Generated by Django 6.1.1 on 2026-10-06 05:54

import services.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(upload_to=services.validators.generate_safe_media_filename, validators=[services.validators.validate_uploaded_image]),
        ),
    ]
