# Generated by Django 6.1.1 on 2026-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
