
import os
import sys
import time
from pathlib import Path

# ---------------------------------------------------------
# Add the Django project root to Python's import path
# ---------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------
# Configure Django
# ---------------------------------------------------------

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django

django.setup()

# ---------------------------------------------------------
# Imports that require Django to be initialized
# ---------------------------------------------------------

import psutil

from django.contrib.auth.models import User
from django.db import connection, reset_queries
from django.test import override_settings
from django.test.utils import CaptureQueriesContext

from rest_framework.test import APIClient

from services.models import Booking, Service


# ---------------------------------------------------------
# Measure one API request
# ---------------------------------------------------------

def measure_request(name, client, method, url, data=None):
    """
    Measure:

    1. HTTP response status
    2. Response time
    3. Database query count
    4. CPU usage
    5. Memory usage
    """

    process = psutil.Process(os.getpid())

    # Start CPU measurement
    process.cpu_percent(interval=None)

    # Memory before request
    memory_before = (
        process.memory_info().rss / (1024 * 1024)
    )

    # Clear previous database query information
    reset_queries()

    # Start timer
    start = time.perf_counter()

    # Capture database queries generated by this request
    with CaptureQueriesContext(connection) as queries:

        if method == "GET":
            response = client.get(url)

        elif method == "POST":
            response = client.post(
                url,
                data=data or {},
                format="json",
            )

        else:
            raise ValueError(
                f"Unsupported HTTP method: {method}"
            )

    # Stop timer
    end = time.perf_counter()

    # CPU after request
    cpu_percent = process.cpu_percent(interval=0.1)

    # Memory after request
    memory_after = (
        process.memory_info().rss / (1024 * 1024)
    )

    # Calculate response time
    response_time_ms = (
        end - start
    ) * 1000

    # Number of database queries
    query_count = len(queries)

    print()
    print("=" * 70)
    print(name)
    print("=" * 70)

    print(
        f"HTTP status       : {response.status_code}"
    )

    print(
        f"Response time     : "
        f"{response_time_ms:.2f} ms"
    )

    print(
        f"Database queries  : "
        f"{query_count}"
    )

    print(
        f"CPU usage         : "
        f"{cpu_percent:.2f}%"
    )

    print(
        f"Memory before     : "
        f"{memory_before:.2f} MB"
    )

    print(
        f"Memory after      : "
        f"{memory_after:.2f} MB"
    )

    print(
        f"Memory change     : "
        f"{memory_after - memory_before:+.2f} MB"
    )

    return {
        "name": name,
        "status": response.status_code,
        "response_time_ms": response_time_ms,
        "queries": query_count,
        "cpu_percent": cpu_percent,
        "memory_before_mb": memory_before,
        "memory_after_mb": memory_after,
        "memory_change_mb": (
            memory_after - memory_before
        ),
    }


# ---------------------------------------------------------
# Main performance test
# ---------------------------------------------------------

@override_settings(
    ALLOWED_HOSTS=[
        "testserver",
        "localhost",
        "127.0.0.1",
    ]
)
def main():

    print()
    print("PERFORMANCE BASELINE")
    print("=" * 70)

    # -----------------------------------------------------
    # Find an existing active user
    # -----------------------------------------------------

    customer = (
        User.objects
        .filter(is_active=True)
        .order_by("id")
        .first()
    )

    if not customer:

        print(
            "ERROR: No active user exists "
            "in the database."
        )

        return

    print(
        f"Using test user: "
        f"{customer.username}"
    )

    # -----------------------------------------------------
    # Create API client
    # -----------------------------------------------------

    client = APIClient()

    # Authenticate the client directly.
    #
    # This allows us to measure the protected APIs
    # without measuring JWT authentication overhead.
    client.force_authenticate(
        user=customer
    )

    # -----------------------------------------------------
    # Find an existing service
    # -----------------------------------------------------

    service = (
        Service.objects
        .select_related(
            "provider",
            "category",
        )
        .filter(status=True)
        .first()
    )

    # If no active service exists,
    # use any existing service.
    if not service:

        service = (
            Service.objects
            .select_related(
                "provider",
                "category",
            )
            .first()
        )

    if not service:

        print(
            "ERROR: No service exists "
            "in the database."
        )

        return

    print(
        f"Using service: "
        f"{service.name}"
    )

    print(
        f"Service ID: "
        f"{service.id}"
    )

    # -----------------------------------------------------
    # Store results
    # -----------------------------------------------------

    results = []

    # -----------------------------------------------------
    # 1. SERVICE SEARCH
    # -----------------------------------------------------

    results.append(
        measure_request(
            name="1. Service Search",
            client=client,
            method="GET",
            url="/api/v1/services/?page=1",
        )
    )

    # -----------------------------------------------------
    # 2. NOTIFICATIONS
    # -----------------------------------------------------

    results.append(
        measure_request(
            name="2. Notifications",
            client=client,
            method="GET",
            url="/api/v1/services/notifications/",
        )
    )

    # -----------------------------------------------------
    # 3. BOOKING HISTORY
    # -----------------------------------------------------

    results.append(
        measure_request(
            name="3. Booking History",
            client=client,
            method="GET",
            url="/api/v1/bookings/",
        )
    )

    # -----------------------------------------------------
    # 4. SERVICE DETAIL
    # -----------------------------------------------------

    results.append(
        measure_request(
            name="4. Service Detail",
            client=client,
            method="GET",
            url=f"/api/v1/services/{service.id}/",
        )
    )

    # -----------------------------------------------------
    # Find an existing booking
    # -----------------------------------------------------

    booking = (
        Booking.objects
        .filter(customer=customer)
        .select_related(
            "service",
            "provider",
        )
        .order_by("-created_at")
        .first()
    )

    if booking:

        print()
        print(
            "Existing booking found:"
        )

        print(
            f"Booking ID: "
            f"{booking.id}"
        )

        print(
            f"Booking status: "
            f"{booking.status}"
        )

    else:

        print()
        print(
            "No existing booking found."
        )

    # -----------------------------------------------------
    # Final results table
    # -----------------------------------------------------

    print()
    print()
    print("=" * 100)

    print(
        "INITIAL PERFORMANCE BASELINE RESULTS"
    )

    print("=" * 100)

    print(
        f"{'API':<25}"
        f"{'Status':<10}"
        f"{'Time(ms)':<15}"
        f"{'Queries':<12}"
        f"{'CPU %':<12}"
        f"{'Memory MB':<15}"
    )

    print("-" * 100)

    for result in results:

        print(
            f"{result['name']:<25}"
            f"{result['status']:<10}"
            f"{result['response_time_ms']:<15.2f}"
            f"{result['queries']:<12}"
            f"{result['cpu_percent']:<12.2f}"
            f"{result['memory_after_mb']:<15.2f}"
        )

    print("=" * 100)


# ---------------------------------------------------------
# Run the benchmark
# ---------------------------------------------------------

if __name__ == "__main__":
    main()

